ALTER TABLE users CHANGE COLUMN documentId document VARCHAR(14); 

ALTER TABLE users ADD IF NOT EXISTS pass VARCHAR(100) NOT NULL;

ALTER TABLE users ADD IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE users ADD IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE users ADD IF NOT EXISTS deleted_at TIMESTAMP;