// Code generated by mockery v2.42.0. DO NOT EDIT.

package interfaces

import (
	entity "pet-dex-backend/v2/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockPetRepository is an autogenerated mock type for the PetRepository type
type MockPetRepository struct {
	mock.Mock
}

type MockPetRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPetRepository) EXPECT() *MockPetRepository_Expecter {
	return &MockPetRepository_Expecter{mock: &_m.Mock}
}

// FindById provides a mock function with given fields: id
func (_m *MockPetRepository) FindById(id int) (*entity.Pet, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *entity.Pet
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*entity.Pet, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *entity.Pet); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Pet)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPetRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockPetRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - id int
func (_e *MockPetRepository_Expecter) FindById(id interface{}) *MockPetRepository_FindById_Call {
	return &MockPetRepository_FindById_Call{Call: _e.mock.On("FindById", id)}
}

func (_c *MockPetRepository_FindById_Call) Run(run func(id int)) *MockPetRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockPetRepository_FindById_Call) Return(_a0 *entity.Pet, _a1 error) *MockPetRepository_FindById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPetRepository_FindById_Call) RunAndReturn(run func(int) (*entity.Pet, error)) *MockPetRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: pet
func (_m *MockPetRepository) Save(pet entity.Pet) error {
	ret := _m.Called(pet)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Pet) error); ok {
		r0 = rf(pet)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPetRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockPetRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - pet entity.Pet
func (_e *MockPetRepository_Expecter) Save(pet interface{}) *MockPetRepository_Save_Call {
	return &MockPetRepository_Save_Call{Call: _e.mock.On("Save", pet)}
}

func (_c *MockPetRepository_Save_Call) Run(run func(pet entity.Pet)) *MockPetRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entity.Pet))
	})
	return _c
}

func (_c *MockPetRepository_Save_Call) Return(_a0 error) *MockPetRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPetRepository_Save_Call) RunAndReturn(run func(entity.Pet) error) *MockPetRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPetRepository creates a new instance of MockPetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPetRepository {
	mock := &MockPetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
