name: golangci-lint

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

env:
  GO_VERSION: stable
  GOLANGCI_LINT_VERSION: v1.59

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: run go lint
        uses: golangci/golangci-lint-action@v6

