name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup deps
        uses: devhatt/workflows/.github/actions/go-setup@main

      - name: run go lint
        uses: golangci/golangci-lint-action@v6

  test:
    runs-on: ubuntu-latest
    needs:
      - golangci-lint
    steps:
      - uses: actions/checkout@v3

      - name: Setup deps
        uses: devhatt/workflows/.github/actions/go-setup@main

      - name: Test
        run: go test ./...

  build:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4

      - name: Setup deps
        uses: devhatt/workflows/.github/actions/go-setup@main

      - name: Run Docker Compose Prod
        run: |
          docker compose --profile integration-tests up -d

      - name: Up migrations
        run: |
          go run cmd/main.go -up

      - name: Check Docker Containers
        run: docker compose ps --services | xargs -I {} sh -c 'docker compose ps {} | grep "Up" || exit 1'
